export PATH="$HOME/.local/bin:/usr/bin:/bin:$PATH"


# open the fuck alias fix previous command error
eval $(thefuck --alias)


### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

#==========Starship Prompt ==========
zinit ice as"command" from"gh-r" \
          atclone"./starship init zsh > init.zsh; ./starship completions zsh > _starship" \
          atpull"%atclone" src"init.zsh"
zinit light starship/starship

#==========First add zsh-autosuggestions after Prompt
zinit ice wait lucid atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

#==========Alias ==========
alias sz='source ~/.zshrc'
alias vz='vim ~/.zshrc'
alias ds='docker ps'
alias ls='ls --color=auto'

#========== OMZ Plugins==========
zinit wait lucid for \
    OMZ::plugins/extract/extract.plugin.zsh \
	  OMZ::lib/history.zsh \
	  OMZ::lib/completion.zsh \
    OMZ::plugins/docker-compose \
    OMZ::plugins/git \
    OMZ::plugins/sudo \

#==========Other Source Plugins==========

zinit light-mode lucid for \
    skywind3000/z.lua \
    Aloxaf/fzf-tab \
    zsh-users/zsh-completions \
    zdharma-continuum/fast-syntax-highlighting \
    chriskempson/base16-shell \
    djui/alias-tips 

